### ISSUE TITLE
Unexpected token: error on Meteor

### ISSUE THREAD

**Issue by jpmelnik** [KyleAMathews/react-spinkit#42]
`W20160922-18:00:40.062(-3)? (STDERR) /home/user/projects/name/name/node_modules/react-spinkit/css/fade-in.css:1
W20160922-18:00:40.255(-3)? (STDERR) (function (exports, require, module, __filename, __dirname) { @-webkit-keyframes fade-in {
W20160922-18:00:40.257(-3)? (STDERR)                                                               ^
W20160922-18:00:40.258(-3)? (STDERR)          
W20160922-18:00:40.258(-3)? (STDERR) SyntaxError: Unexpected token ILLEGAL
W20160922-18:00:40.259(-3)? (STDERR)     at exports.runInThisContext (vm.js:53:16)
W20160922-18:00:40.259(-3)? (STDERR)     at Module._compile (module.js:373:25)
W20160922-18:00:40.261(-3)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20160922-18:00:40.263(-3)? (STDERR)     at Module.load (module.js:343:32)
W20160922-18:00:40.264(-3)? (STDERR)     at Module.Mp.load (/root/.meteor/packages/babel-compiler/.6.9.1.qmu614++os+web.browser+web.cordova/npm/node_modules/reify/node/runtime.js:16:23)
W20160922-18:00:40.265(-3)? (STDERR)     at Function.Module._load (module.js:300:12)
W20160922-18:00:40.266(-3)? (STDERR)     at Module.require (module.js:353:17)
W20160922-18:00:40.268(-3)? (STDERR)     at require (internal/module.js:12:17)
W20160922-18:00:40.270(-3)? (STDERR)     at Object.<anonymous> (/home/username/projects/name/name/node_modules/react-spinkit/dist/index.js:19:1)
W20160922-18:00:40.271(-3)? (STDERR)     at Module._compile (module.js:409:26)
`

**Comment by KyleAMathews** [comment]
react-spinkit requires its own css. It looks like support for this is added in Meteor 1.3 http://stackoverflow.com/questions/34553267/how-to-require-css-file-using-npm-and-meteor
